const http = require('http');
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const PORT = process.env.PORT || 3000;
const PUBLIC_DIR = path.join(__dirname, 'public');

const MIME_TYPES = {
  '.html': 'text/html',
  '.css': 'text/css',
  '.js': 'text/javascript',
  '.json': 'application/json',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.svg': 'image/svg+xml'
};

const server = http.createServer((req, res) => {
  const url = req.url;

  // Serve static files
  let filePath = path.join(PUBLIC_DIR, url === '/' ? 'index.html' : url);
  const ext = path.extname(filePath);

  if (fs.existsSync(filePath) && fs.statSync(filePath).isFile()) {
    const contentType = MIME_TYPES[ext] || 'text/plain';
    res.writeHead(200, { 'Content-Type': contentType });
    fs.createReadStream(filePath).pipe(res);
    return;
  }

  // API Endpoints
  if (req.method === 'POST' && url === '/api/generate-script') {
    let body = '';
    req.on('data', chunk => body += chunk);
    req.on('end', () => {
      try {
        const { username, repo, backdateDays, minCommits, maxCommits, randomness } = JSON.parse(body);

        const ps1Content = `# GitHub Streak Booster PowerShell Script
# Generated by GitHub Profile Craft & Streak Booster

$username = "${username || 'TaHoang715'}"
$repo = "${repo || 'streak-booster'}"
$backdateDays = ${backdateDays || 100}
$minCommits = ${minCommits || 1}
$maxCommits = ${maxCommits || 5}
$randomness = ${randomness || 85}

Write-Host "🚀 Starting GitHub Streak Booster for $username..." -ForegroundColor Cyan

$startDate = (Get-Date).AddDays(-$backdateDays)

for ($i = 0; $i -le $backdateDays; $i++) {
    $currentDate = $startDate.AddDays($i)
    $chance = Get-Random -Minimum 1 -Maximum 101

    if ($chance -le $randomness) {
        $commitsCount = Get-Random -Minimum $minCommits -Maximum ($maxCommits + 1)
        for ($c = 1; $c -le $commitsCount; $c++) {
            $dateStr = $currentDate.ToString("yyyy-MM-dd HH:mm:ss")
            $env:GIT_COMMITTER_DATE = $dateStr
            $env:GIT_AUTHOR_DATE = $dateStr

            "Update activity history log: $dateStr" | Out-File -FilePath history.txt -Append -Encoding utf8
            git add history.txt
            git commit -m "chore(streak): automated activity record [$dateStr]" --quiet
        }
    }
}

Write-Host "✅ Streak boost complete! Don't forget to run: git push origin main" -ForegroundColor Green
`;

        fs.writeFileSync(path.join(__dirname, 'boost.ps1'), ps1Content, 'utf-8');

        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ success: true, message: 'Script boost.ps1 generated successfully!' }));
      } catch (err) {
        res.writeHead(500, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ success: false, error: err.message }));
      }
    });
    return;
  }

  res.writeHead(404, { 'Content-Type': 'text/plain' });
  res.end('Not Found');
});

server.listen(PORT, () => {
  console.log(`\n🚀 GitHub Profile Craft & Streak Booster Dashboard running at:`);
  console.log(`👉 http://localhost:${PORT}\n`);
});
